language: clojure
env:
  global:
  - COMMIT: ${TRAVIS_COMMIT::7}
  - ARTIFACTORY_USER: travis-mvn-deploy
  - secure: OSBROmAeiRK6kJyuFtc+13JavrBY+xfGR9jxBrB78KT7OWJ5Bj9L3BHdS/ljGfkSvrrZV+KUYKG6BLrGUyQBgcevSB0IelpQjE2V2YtL2aTamzLA/8Urb4cqJYP2nMpAQL7oCEhlVvn5gJcmZL/Ej/m0YRUhaiZ2p+YVlE7CSNXW61BsYd5tgYoQd/owjWGMainbbQtu96pcqhwEPDs5elw5C6/Oe2N3ya/C4WGUYv+yt2vPVQWaMfTP5WPtBzsjJ8kVPdFZFgsAAwfHWLd/GrVaTap1PLLzvh3sP3x4TZtOpGJKq3Kw/HS+7IbsV7QW/p+Ogp9JvsTgQu7ZYvjffOt6SCH/efpJoOyJgp3yeD+mcG6vOjEpH5ZOFAWqKUzYlklDVBJlir2l/YzP2OUT0fNwTNXmlCnTEBsiP6S8ex5Jx0I07W6LrxDcPYjrBzXahTirZ4rsYb0jvurDVEy/2gI7BzAINTqDHWmZG02Ys5sGlXH2gYq8sDhV7KYG/1nMCBPPYTWz1Q6LvOHhSo/jG8v5vkmI4zIh+lxYzNMLZ884SiKRzp647c6DmxH4U6fq9KsgtUdChriYc0xZa+gJbZ9wvigdERC9rul1OkkG28dACjCs2FWZNe6AUCaV+uIh0Vi2gKPTkcY73RLBfM7/mASyjKb6y8Jgei55sanBBTQ=
script: ./travis-build-deploy.sh
branches:
  only:
  - master
  - develop
jdk:
- oraclejdk8
notifications:
  slack: atomist:djCbqLfRUUwivr2pXqtByTn9
  email: false
cache:
  directories:
  - $HOME/.m2
